// src/i18n.js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Til konfiguratsiyasi
i18n.use(initReactI18next).init({
    resources: {
        uz: {
            translation: {
                "why_us": "Nega aynan biz?",
                "license": "Litsenziya",
                "video_collection": "VIDEO JAMLANMA",
                "our_address": "Bizning manzil",
                "address_details": "Amir Temur shox ko'chasi, 107 B-uy, Toshkent, O'zbekiston",
                "phone": "Telefon",
                "nursing_program_title": "HAMSHIRALARNI O'QITISH DASTURI",
                "nursing_schedule": "DARS JADVALI",
                "nursing_days": "Haftada 3 kun",
                "nursing_hours": "4 soat",
                "acupuncture_program_title": "IGNA REFLEKSOTERAPIYASI O'QITISH DASTURI",
                "acupuncture_days": "Haftada 5 kun",
                "teaching_info": "Bizning Shifokor tibbiy o‘quv markazimizda sizga ko‘p yillik tajribaga ega o‘qituvchilar tomonidan darslar o‘tiladi.",
                "certification_info": "Kurs yakunida bitiruvchilarga sertifikatlar beriladi.",
                "experience_info": "Bizning o‘qituvchilarimiz orasida 35 yil va undan ortiq tajribaga ega mutaxassislar mavjud.",
                "nursing_title": "HAMSHIRALARNI O‘QITISH",
                "nursing_mode": "Oflayn",
                "nursing_teacher": "Hodjaqulova Nasiba Sharofiddinovna",
                "nursing_cta": "Malaka oshirish kurslariga yoziling va bilim ko‘nikmalaringizni yanada oshiring",
                "small_groups": "5 kishilik kichik guruhlar",
                "teacher_label": "O’qituvchi",
                "learn_more": "Batafsil",
                "center_name": "Shifokor O‘quv Markazi",
                "center_description": "Hamshiralik va akupunktura kurslari uchun ro‘yxatdan o‘ting.",
                "course_title": "MALAKA OSHIRISH",
                "course_subtitle": "KURSLARI",
                "course_description": "Malaka oshirish kurslarini 35 yillik tajribaga ega Hodjaqulova Nasiba Sharofiddinovna tomonidan o’tiladi.",
                "orderbuton": "Bron qilish",
                "customer_opinion_title": "MIJOZLAR FIKRI",
                "customer_opinion_subtitle": "Mijoz fikri",
                "review_1": "Xonalar juda qulay va toza, xizmatdan mamnun qoldim.",
                "review_2": "24/7 xizmat juda qulay, tavsiya qilaman!",
                "review_3": "Narxi arzon, sifati yuqori! Yana kelaman.",
                "contact": "Bog'lanish",
                "contactManager": "Menejer bilan bog'lanish",
                "followus": "Tarmoqlar",
                "niceser": " Bizning Hostel barcha qulayliklarga ega !",
                "ourhostel": "Bizning Hostel",
                "takeTour": "Mavjud",
                "rooms": "Xonalar",
                "services": "Xizmatlar",
                "gallery": "Galereya",
                "location1": "Joylashuv",
                "our_links": "Linklar",
                "service_capacity": "1000 ta odamga xizmat",
                "rooms1": "170 ta xona",
                "parking": "Avtoturargoh mavjud",
                "room_cleanliness": "Xonalar juda toza va zamonaviy. Har kuni tozalash xizmati mavjud, hammomdagi jihozlar esa yangicha. O‘zimni uyimdagidek his qildim.",
                "staff_courtesy": "Ro‘yxatdan o‘tishda va qolish davomida xodimlar doimo iltifotli bo‘lishdi. Har qanday savolimga tez javob oldim. Resepsiyadagi yigitlarga alohida rahmat!",
                "location": "Hostel shahar markazida joylashgan, yaqin atrofda do‘konlar, restoranlar va jamoat transporti mavjud. Ish safari uchun ayni muddao bo‘ldi.",
                "priceroom": "Narxi juda hamyonbop, ayniqsa qisqa muddatli qolish uchun mos. Balki nonushta menyusi biroz boyroq bo‘lishi mumkin edi, lekin umuman olganda yaxshi tajriba bo‘ldi.",
                "buy_your_dream_apartment": "Orzuingizdagi kvartirani xarid qiling",
                "we_sell_apartments": "Biz sizning shahringizda ajoyib kvartiralarni sotamiz. Ariza qoldiring yoki takliflar bilan tanishing",
                "searching_apartment": "Hostel izlayabsizmi ? Joyni bron qiling biz siga qayta aloqaga chiqamiz.",
                "trial_period": "15 kunlik sinov muddati",
                "price40": "40 000 so'm",
                "price35": "35 000 so'm",
                "doubleRoom": "2 kishilik xonalar",
                "standardRoom": "Oddiy Xona",
                "specialOffer": "Maxsus taklif",
                "special": "Maxsus",
                "bronqilish": "BRON QILISH",
                "comennts": "IZOHLAR",
                "parners": "HAMKORLAR",
                "rooms": "XONALAR",
                "hostel_welcome": " Qatortol Savdo Hostel",
                "hotel_intro": "        Mehmonxona shahar markazida joylashgan, ko‘plab do‘kon va restoranlarga yaqin joyda joylashgan. Ushbu zamonaviy mehmonxona sizga misli ko‘rilmagan hashamatni taqdim etadi. ",
                "rooms_title": "Barcha xonalarimiz",
                "rooms_description": "Har bir xona qulaylik va nafislikni hisobga olgan holda loyihalashtirilgan bo‘lib, sizning dam olishingiz uchun barcha zarur sharoitlarga ega.",
                "customer_opinion": "Mijozlarimiz fikri biz uchun juda muhim.",
                "furniture_quality": "Bizning barcha mebellarimiz mijozlarimiz uchun eng yaxshi materiallar va tanlovlardan foydalanadi.",
                "partners": "Bizning hamkorlar",
                "comment": "Izoh",
                "leaveComment": "Izoh qoldiring",
                "language": "🇺🇿 /",
                "orderButton": "BUYURTMA",
                "orderTitle": "Buyurtma berish",
                "namePlaceholder": "Ismingiz",
                "phonePlaceholder": "Telefon raqamingiz",
                "emailPlaceholder": "Email manzilingiz",
                "submitButton": "Yuborish",
                "closeButton": "Yopish",
                "aboutUs": "BIZ HAQIMIZDA",
                "images": "RASIMLAR",
                "advantages": "AFZALLIKLAR",
                "booking": "BRON QILISH",
                "contacts": "KONTAKTLAR",
                "hotelDescription": "Payitaxt Hotel Andijondagi eng zamonaviy va hashamatli mehmonxona hisoblanadi.",
                "hotelLocation": "Mehmonxona shahar markaziga yaqin, Ko'plab do'kon va restoranlarga yaqin joyda joylashgan. Masjidga juda yaqin. Ushbu zamonaviy mehmonxona sizga misli ko'rilmagan hashamatni taqdim etadi. Bizning xodimlarimiz sizga sifatli xizmat ko'rsatish va unutilmas dam olishni ta'minlash uchun kechayu kunduz ishlaydi. Va barcha ehtiyojlaringizni qondirishga intiladi. Sizni kutib olishni intiqlik bilan kutamiz!",
                "preOrder": "Bron qilish",
                "price": "500000 so'm",
                "benefits": "AFZALLIKLAR",
                "specialFeatures": "HOSTELDAGI QULAYLIKLAR",
                "cozyRooms": "Shinam xonalar",
                "kitchen": "Oshxona",
                "roomService": "Xona xizmati",
                "conferenceRoom": "Konferentsiya xonasi",
                "twentyFourSeven": "24/7 ish faoliyati",
                "freeParking": "Bepul avto turargoh",
                "facilities": "IMKONIYAT",
                "guests": "MEXMONLAR",
                "rooms": "XONALAR",
                "separateSections": "Ayollar va erkaklar uchun alohida bo'lim mavjud",
                "metroDistance": "METRO VA MASJIDGACHA BO'LGAN MASOFA",
                "nearestMetro": "Eng yaqin metro <br/> Mirzo Ulug'bek va Novza",
                "nearestMosque": "Masjiddan",
                "contactUs": "Biz bilan bog‘lanish",
                "yourMessage": "Xabaringiz",
                "writeYourMessage": "Xabaringizni bu yerga yozing",
                "sendRequest": "Arizangizni yuboring",
                "tashkent": "Toshkent, Qtortol",
                "ourLinks": "BIZNING HAVOLALARIMIZ",
                "manager": "MENEJER",
                "wifi_tv_service": "Honalarda barcha sharoitlar mavjud",
                "best_location": "Toshkent shahar markazida joylashgan. Yaqin atrofda: Masjid, Metro, Magazinlar",
                "restaurant_food": "Barcha qulayliklarga ega oshxona",
                "parking_info": "Bepul avtoturargoh ",
                "title_best_place": "Qulay joylashuv",
                "title_restaurants": "Oshxona",
                "title_parking": "Avtoturargoh",
                "title_comfort_room": "Shinam honalar",
                "daily_cleaning": "Kundalik tozalash",
                "bathroom": "Dush",
                "person": "1000 ta odamlarga xizmat",
                "parkings": "Avtoturargoh",
                "xona": "170 xona",
                "about1": "Bizning mehmonxonamiz bugungi kungacha 1000 dan ortiq mijozga sifatli xizmat ko‘rsatgan.",
                "about2": "Siz uchun zamonaviy qulayliklarga ega 170 ta xona tayyorlangan.",
                "about3": "Kun-u tun, haftaning har kuni — sizga yordam berishga tayyormiz.",
                "about4": "Mehmonlarimiz uchun bepul va xavfsiz avtoturargoh mavjud."
            }
        },
        ru: {
            translation: {
                "why_us": "Почему именно мы?",
                "license": "Лицензия",
                "video_collection": "ВИДЕОПОДБОРКА",
                "our_address": "Наш адрес",
                "address_details": "Улица Амира Темура, дом 107B, Ташкент, Узбекистан",
                "phone": "Телефон",
                "nursing_program_title": "ПРОГРАММА ОБУЧЕНИЯ МЕДСЕСТЁР",
                "nursing_schedule": "РАСПИСАНИЕ ЗАНЯТИЙ",
                "nursing_days": "3 дня в неделю",
                "nursing_hours": "4 часа",
                "acupuncture_program_title": "ПРОГРАММА ОБУЧЕНИЯ ИГЛОРЕФЛЕКСОТЕРАПИИ",
                "acupuncture_days": "5 дней в неделю",
                "teaching_info": "В нашем медицинском учебном центре Shifokor занятия проводят преподаватели с многолетним опытом.",
                "certification_info": "По окончании курса выпускникам выдаются сертификаты.",
                "experience_info": "Среди наших преподавателей есть специалисты с более чем 35-летним опытом.",
                "nursing_title": "ОБУЧЕНИЕ МЕДСЕСТЁР",
                "nursing_mode": "Офлайн",
                "nursing_teacher": "Ходжакулова Насиба Шарофиддиновна",
                "nursing_cta": "Запишитесь на курсы повышения квалификации и улучшите свои знания и навыки",
                "small_groups": "Маленькие группы по 5 человек",
                "teacher_label": "Преподаватель",
                "learn_more": "Подробнее",
                "center_name": "Учебный Центр Шифокор",
                "center_description": "Запишитесь на курсы по сестринскому делу и акупунктуре.",
                "course_title": "ПОВЫШЕНИЕ КВАЛИФИКАЦИИ",
                "course_subtitle": "КУРСЫ",
                "course_description": "Курсы повышения квалификации проводит Ходжакулова Насиба Шарофиддиновна, имеющая 35-летний опыт.",
                "orderbuton": "Бронирование",
                "customer_opinion_title": "МНЕНИЕ КЛИЕНТОВ",
                "customer_opinion_subtitle": "Отзывы клиентов",
                "review_1": "Номера очень удобные и чистые, я остался доволен обслуживанием.",
                "review_2": "Круглосуточное обслуживание — это очень удобно, рекомендую!",
                "review_3": "Цены доступные, качество на высоте! Обязательно приеду снова.",
                "contact": "Связь",
                "contactManager": "Связаться с менеджером",
                "followus": "Сети",
                "niceser": " В нашем хостеле есть все удобства!",
                "ourhostel": "Наш Хостел",
                "takeTour": "Есть",
                "rooms": "Номера",
                "services": "Услуги",
                "gallery": "Галерея",
                "location": "Расположение",
                "our_links": "Ссылки",
                "service_capacity": "Обслуживание для 1000 человек",
                "rooms1": "170 номеров",
                "parking": "Парковка доступна",
                "room_cleanliness": "Номера очень чистые и современные. Каждый день проводится уборка, а сантехника в ванной новая. Я чувствовал себя как дома.",
                "staff_courtesy": "Во время регистрации и всего пребывания персонал всегда был вежлив. На все вопросы я получал быстрые ответы. Особая благодарность сотрудникам на ресепшн!",
                "location": "Отель находится в центре города, рядом магазины, рестораны и общественный транспорт. Это было идеальное место для моей деловой поездки.",
                "priceroom": "Цена очень доступная, особенно для краткосрочного пребывания. Завтрак мог бы быть более разнообразным, но в целом это был отличный опыт.",
                "buy_your_dream_apartment": "Купите квартиру своей мечты",
                "we_sell_apartments": "Мы продаём прекрасные квартиры в вашем городе. Оставьте заявку или ознакомьтесь с предложениями",
                "searching_apartment": "Вы ищете хостел? Забронируйте место, и мы свяжемся с вами.",
                "trial_period": "от 15 дней пробный период",
                "price40": "40 000 сумов",
                "price35": "35 000 сумов",
                "doubleRoom": "Двухместные номера",
                "standardRoom": "Стандартный номер",
                "specialOffer": "Специальное предложение",
                "special": "Специальный",
                "bronqilish": "БРОНИРОВАНИЕ",
                "comennts": "ПРИМЕЧАНИЯ",
                "parners": "ПАРТНЕРЫ",
                "rooms": "КОМНАТЫ",
                "hostel_welcome": " хостел!",
                "hotel_intro": " Отель расположен рядом с центром города, вблизи множества магазинов и ресторанов. Также находится очень близко к мечети. Этот современный отель предлагает вам непревзойденную роскошь.",
                "rooms_title": "Все наши номера",
                "rooms_description": "Каждый номер оформлен с учетом комфорта и элегантности, предлагая всё необходимое для вашего спокойного отдыха.",
                "customer_opinion": "Мнения наших клиентов очень важны для нас.",
                "furniture_quality": "Вся наша мебель изготавливается из лучших материалов и с учетом предпочтений клиентов.",
                "partners": "Наши партнеры",
                "comment": "Комментарий",
                "leaveComment": "Оставьте комментарий",
                "language": "🇺🇿 /",
                "orderButton": "ЗАКАЗ",
                "orderTitle": "Оформить заказ",
                "namePlaceholder": "Ваше имя",
                "phonePlaceholder": "Ваш номер телефона",
                "emailPlaceholder": "Ваш email",
                "submitButton": "Отправить",
                "closeButton": "Закрыть",
                "aboutUs": "О НАС",
                "images": "ФОТОГРАФИИ",
                "advantages": "ПРЕИМУЩЕСТВА",
                "booking": "БРОНЬ",
                "contacts": "КОНТАКТЫ",
                "hotelDescription": "Отель Payitaxt является самым современным и роскошным отелем в Андижане.",
                "hotelLocation": "Отель расположен в центре города, рядом с многочисленными магазинами и ресторанами. Очень близко к мечети. Этот современный отель предлагает вам несравненную роскошь. Наши сотрудники работают круглосуточно, чтобы предоставить вам качественное обслуживание и обеспечить незабываемый отдых. Они стремятся удовлетворить все ваши потребности. Мы с нетерпением ждем встречи с вами!",
                "preOrder": "ЗАРАНЕЕ ЗАКАЗАТЬ",
                "price": "500000 сум",
                "benefits": "ПРЕИМУЩЕСТВА",
                "specialFeatures": "УСЛУГИ В ХОСТЕЛЕ",
                "cozyRooms": "Уютные комнаты",
                "kitchen": "Кухня",
                "roomService": "Обслуживание номеров",
                "conferenceRoom": "Конференц-зал",
                "twentyFourSeven": "Работаем 24/7",
                "freeParking": "Бесплатная парковка",
                "facilities": "УДОБСТВА",
                "guests": "ГОСТИ",
                "rooms": "НОМЕРА",
                "separateSections": "Отдельные зоны для женщин и мужчин",
                "metroDistance": "РАССТОЯНИЕ ДО МЕТРО И МЕЧЕТИ",
                "nearestMetro": "Ближайшие станции метро <br/> Мирзо-Улугбек и Новза",
                "nearestMosque": "От мечети",
                "contactUs": "Связаться с нами",
                "yourMessage": "Ваше сообщение",
                "writeYourMessage": "Напишите ваше сообщение здесь",
                "sendRequest": "Отправить запрос",
                "tashkent": "Ташкент, Квартал",
                "ourLinks": "НАШИ ССЫЛКИ",
                "manager": "МЕНЕДЖЕР",
                "wifi_tv_service": "В номерах есть все удобства.",
                "best_location": "Расположен в центре города Ташкента. Рядом: Мечеть, Метро, ​​Магазины",
                "restaurant_food": "Кухня со всеми удобствами",
                "parking_info": "Предоставляется бесплатная парковка.",
                "title_best_place": "Лучшее место",
                "title_restaurants": "Кухня",
                "title_parking": "Парковка",
                "title_comfort_room": "Номер Комфорт",
                "daily_cleaning": "Ежедневная уборка",
                "bathroom": "Душ",
                "person": "Мы обслуживаем 1000 человек",
                "parkings": "парковка",
                "xona": "170 номеров",
                "about1": "На сегодняшний день наш отель предоставил качественные услуги более чем 1000 клиентам.",
                "about2": "Для Вас подготовлено 170 номеров с современными удобствами.",
                "about3": "Мы готовы помочь вам днем ​​и ночью, каждый день недели.",
                "about4": "Нашим гостям предоставляется бесплатная и охраняемая парковка."

            }
        }
    },
    lng: "uz", // default language
    fallbackLng: "uz", // default fallback language
    interpolation: {
        escapeValue: false, // React already safes from xss
    },
});

export default i18n;